### ISSUE TITLE
Getting error while installing your Project inside mine.

### ISSUE THREAD

**Issue by vishal-iosdeveloper** [imoreapps/ffmpeg-avplayer-for-ios-tvos#1]
Hi, 
I am using your library since ago. After update i got below error:

ld: cannot link directly with /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/usr/lib/system/libdyld.dylib.  Link against the umbrella framework 'System.framework' instead. for architecture x86_64

**Comment by imoreapps** [comment]
Please don't link with the "System.framework" framework.

**Comment by vishal-iosdeveloper** [comment]
After added below libraries,
1. libz.tbd
2. libstdc++.tbd
3. libiconv.tbd
4. libbz2.tbd 
Salved my issue. Don't add "libdyld.dylib".

**Comment by vishal-iosdeveloper** [comment]
It will great help if you can guide me through below:
--> After Managing Play next/previous video,
I am only able to play sound of next video. View remain same for next/previous video, seems View for next/previous video is not loaded.

And View stuck when i tap on screen for hide/Show controls.

**Comment by imoreapps** [comment]
"View stuck when i tap on screen for hide/Show controls."
Please don't test video playback on Simulator. Thanks.

**Comment by vishal-iosdeveloper** [comment]
I also tested in it iPad Device, But same thing happened in there also.
