### ISSUE TITLE
Cocoapods and License 

### ISSUE THREAD

**Issue by batkov** [imoreapps/ffmpeg-avplayer-for-ios-tvos#11]
Hello,

Thanks for great project. It's really interesting, and I want to say thanks to you for providing it.

I just want to ask few questions:
1. What does [AVPLicense register:] stands for? Is it "dolby license"? Also "register" is keyword for xcode, so method with such name better be renamed.
2. What is the License of whole project? I hope it is kind of MIT.
3. Cocoapods. Don't you want to make cocoapods library from your project? It is very simple and very convenient. https://guides.cocoapods.org/contributing/contribute-to-cocoapods.html

**Comment by batkov** [comment]
Really?

**Comment by imoreapps** [comment]
This is a pay framework, it's just a demo to show how to use the framework for our customers. If you want to use it in your products, please purchase the license of the framework. Thanks.
