### ISSUE TITLE
Seeking not smooth

### ISSUE THREAD

**Issue by ghost** [imoreapps/ffmpeg-avplayer-for-ios-tvos#13]
Use mp4 or mov files e,g from iTunes movies store.
Use seeking in iOS photos app and file hup 3.4
iOS photos app seeking is really smooth. Frame by frame!!

**Comment by imoreapps** [comment]
This is a big challenge for avplayer that's based on the FFmpeg library, we are working hard to improve this on future updates. Thanks.
