### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RLovelett** [imoreapps/ffmpeg-avplayer-for-ios-tvos#15]
I don't see a license anywhere; what is the license?

Since the frameworks are probably the things that actually interface with FFmpeg, where are the sources for those?

**Comment by barkiiqbal** [comment]
did you get your answer? I am also unable to find the license.

**Comment by imoreapps** [comment]
Thanks for your feedback, this is charging framework.

**Comment by RLovelett** [comment]
I was afraid you were going to say that.

I want to go ahead and inform you that I am notifying both the FFmpeg copyright owners and x264 copyright owners. I believe you are violating their copyrights.

[FFmpeg is distributed under the LGPL 2.1](https://www.ffmpeg.org/legal.html) and [x264](https://www.videolan.org/developers/x264.html) under the GPL 2.0. Both of which at the very least require you to redistribute the original source code and license (neither of which you are currently doing).

**Comment by imoreapps** [comment]
Our framework is based on the original FFmpeg (version 2.8) and x264 source code, never modify their original source code.

**Comment by RLovelett** [comment]
If your using x264, which you say you are, it is GPL licensed code. As such, any modifications to software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

**Comment by imoreapps** [comment]
Sorry, in fact our framework only uses the FFmpeg library, not including x264.
