### ISSUE TITLE
Is where any way to get current frame as CVPixelBufferRef

### ISSUE THREAD

**Issue by ZhuchoG** [imoreapps/ffmpeg-avplayer-for-ios-tvos#16]
Hello, i have library for playing 360 degree video, using standard  AVPlayer and AVPlayerItemVideoOutput, and have code like this:

```
- (CVPixelBufferRef)getCurrentFramePicture
{
    CMTime currentTime = [self.videoOutput itemTimeForHostTime:CACurrentMediaTime()];
    [self.delegate progressTimeChanged:currentTime];
    if (![self.videoOutput hasNewPixelBufferForItemTime:currentTime]) {
        return 0;
    }
    CVPixelBufferRef buffer = [self.videoOutput copyPixelBufferForItemTime:currentTime itemTimeForDisplay:NULL];

    return buffer;
}
```

but standard AVPlayer can not play some formats of videos :( I want to try this library, but cant see way to get frame for my texture. Is any? Thank you.

**Comment by Rannie** [comment]
same issue

**Comment by imoreapps** [comment]
Framework can achieve your goal, but it doesn't expose these interfaces for api users yet, really rare requirement.

**Comment by Rannie** [comment]
全景页面很好绘制 如果能够得到 CVPixelBufferRef 的话那我可以直接拿到那个页面上去显示 rtmp 流的画面了。

**Comment by CoderLT** [comment]
+1

**Comment by UriChan** [comment]
@Rannie 这个问题解决了没，我也在弄这个，可以的话加我QQ聊聊357666683
