### ISSUE TITLE
when i use your framework,get some errors.

### ISSUE THREAD

**Issue by wwpp3399** [imoreapps/ffmpeg-avplayer-for-ios-tvos#19]
![qq20160516-1](https://cloud.githubusercontent.com/assets/4317010/15283806/d644176e-1b7f-11e6-912b-043713af04d9.png)
![qq20160516-0](https://cloud.githubusercontent.com/assets/4317010/15283807/d6bbfe14-1b7f-11e6-9192-b6cdd87d1586.png)

can you help me~~,thank you very much!

**Comment by imoreapps** [comment]
It seemed that you have not yet registered any license, please check the method "- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions" of AppDelegate.m file.
