### ISSUE TITLE
Hello, excuse me, I want to get the frequency of the video frequency, how can we get it?

### ISSUE THREAD

**Issue by AllLuckly** [imoreapps/ffmpeg-avplayer-for-ios-tvos#2]
Hello, excuse me, I want to get the frequency of the video frequency, how can we get it?

**Comment by imoreapps** [comment]
Video frequency? Do you mean FPS?

**Comment by AllLuckly** [comment]
Video

**Comment by imoreapps** [comment]
Framework does NOT have such interface to query this info. Thanks.

**Comment by imoreapps** [comment]
The latest version has already supported the FPS, bitrate and Buffering progress informations query.
