### ISSUE TITLE
Ability to move subtitle view

### ISSUE THREAD

**Issue by ghost** [imoreapps/ffmpeg-avplayer-for-ios-tvos#23]
It would be great to have access to the subtitle view, in order to move it, e.g. when the video controls appears so that the controls don't block the subtitle view.

**Comment by imoreapps** [comment]
Great, got it.

**Comment by imoreapps** [comment]
Now framework supports customization for subtitle render. How to do it?

1. prepare yourself subtitle render view, such as UILabel or something else

2. disable the built-in subtitle render component by setting property **enableBuiltinSubtitleRender** of **FFAVPlayerController** component to **NO**.

3. load external subtitle by using **openSubtitleFile** of **FFAVPlayerController** component.

4. render subtitle by yourself in **FFAVPlayerControllerDidSubtitleChange:subtitleItem:** delegate methods of **FFAVPlayerController** component.

That's it.
