### ISSUE TITLE
Improve Seeking

### ISSUE THREAD

**Issue by ghost** [imoreapps/ffmpeg-avplayer-for-ios-tvos#24]
The seeking doesn't work sometimes, especially in the first and last 10 seconds of the video.

It would be okay if the seeking takes a little bit more time but at least seeks to the specified time.

Would be great if you could fix this. Thank you!

**Comment by red010182** [comment]
I'm facing the same problem, in fact, in my case the seek function is totally fail and sometimes leads to crash.

Test video: http://www.mediacollege.com/video-gallery/testclips/20051210-w50s.flv

Any solutions?

**Comment by imoreapps** [comment]
The Latest commit [8dd32aa](https://github.com/iMoreApps/ffmpeg-avplayer-for-ios-tvos/commit/8dd32aa8ea94940407019af5c348d430bbcc2f6e) improved seek operation.
