### ISSUE TITLE
.m3u8 support?

### ISSUE THREAD

**Issue by jiangshanlog** [imoreapps/ffmpeg-avplayer-for-ios-tvos#25]
Use this SDK because it support .rtmp,but also want to support .m3u8,it isn't support?

**Comment by imoreapps** [comment]
Of course, the framework supports m3u8 av source, you can check it by below av sources.

http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
