### ISSUE TITLE
Support for tvOS? not working

### ISSUE THREAD

**Issue by DeepakColworx** [imoreapps/ffmpeg-avplayer-for-ios-tvos#26]
The sample project works perfectly for iOS. but on tvOS, I don't get past to this error 
Error Domain=com.imoreapps.avplayer.errordomain Code=-1499 "(null)" ffmpeg

This error message doesn't tell much. Am i missing something?

Thanks

**Comment by angryDuck2** [comment]
Did you figure this out? Cause I am having the same issue!

**Comment by tanhan** [comment]
How did you figure this out?

**Comment by angryDuck2** [comment]
Finally figured it out. This is a licensed product and needed the license to work. Just got to the demo apps and copy the license from the app delegate class
