### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sebacho-Barajas** [imoreapps/ffmpeg-avplayer-for-ios-tvos#3]
ld: warning: ignoring file /Users/Sebastian/Downloads/ffmpeg-avplayer-for-ios-master/libs/AVPlayerTouch.framework/AVPlayerTouch, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/Sebastian/Downloads/ffmpeg-avplayer-for-ios-master/libs/AVPlayerTouch.framework/AVPlayerTouch
Undefined symbols for architecture arm64:
  "_AVOptionNameAVProbeSize", referenced from:
      -[PlayerViewController viewDidLoad] in PlayerViewController.o
  "_AVOptionNameAVAnalyzeduration", referenced from:
      -[PlayerViewController viewDidLoad] in PlayerViewController.o
  "_AVOptionNameHttpUserAgent", referenced from:
      -[PlayerViewController viewDidLoad] in PlayerViewController.o
  "_OBJC_CLASS_$_FFAVPlayerController", referenced from:
      objc-class-ref in MovieInfosViewController.o
      objc-class-ref in PlayerViewController.o
  "_AVOptionNameAVFormatName", referenced from:
      -[PlayerViewController viewDidLoad] in PlayerViewController.o
  "_OBJC_CLASS_$_AVPLicense", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FFAVParser", referenced from:
      objc-class-ref in MovieInfosViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by imoreapps** [comment]
The framework size has reached the github size limitation, so we zipped the framework to reduce its size, after you cloned the github repo, you can  manually unzip the libs.zip file within the root directory of the project, then try to rebuild it, this error should be gone.

**Comment by Sebacho-Barajas** [comment]
thanks solved it

**Comment by Sebacho-Barajas** [comment]
what do i need to do to add this player to my app?

**Comment by imoreapps** [comment]
Thanks for your feedback. We are making the tutorial now, we believe that it’s coming soon. Now you can reference the github DEMO project. The most you need to do is
1. instance an FFAVPlayerController object
2. setup its delegate and some properties
3. invoke the openMedia method to open an av resource
4. when you received the "did load” event (via delegate), setup UI, the FFAVPlayerController just exposes an UIKit object “drawableView” property, you can do any operations on it just like an normal UIView object.
5. customize yourself player UI and associate UI elements with FFAVPlayerController object.

It’s very similar with iOS MPMoviePlayerController component.

Notice: the framework is not FREE, so if you want to use it in your product, please purchase the license.

Thanks.
