### ISSUE TITLE
when play rtmp url , it shows "failed to load video"

### ISSUE THREAD

**Issue by haofanning** [imoreapps/ffmpeg-avplayer-for-ios-tvos#32]
but i can play the rtmp url on the vlc video

**Comment by ailinykh** [comment]
got the same error
Error Domain=com.imoreapps.avplayer.errordomain Code=-1499 "(null)"

**Comment by ailinykh** [comment]
Oh, it is because of licence
https://github.com/iMoreApps/ffmpeg-avplayer-for-ios-tvos/blob/master/AVPlayerDemo/AppDelegate.m#L17

**Comment by imoreapps** [comment]
Just renew the demo license code, thanks.

**Comment by boardmain** [comment]
hi how renew the demo license???

**Comment by ZvOlCuOk2009** [comment]
I have the same problem. Tell me how to update the license?

**Comment by fukemy** [comment]
how to renew license??

**Comment by imoreapps** [comment]
Ok, we will review this issue asap, if it's license expiration issue, we
will renew it. Thank you very much.

đỗ dũng <notifications@github.com> 于2018年7月9日周一 下午9:04写道：
