### ISSUE TITLE
Cannot get thumbnail using openMedia (open is no longer available)

### ISSUE THREAD

**Issue by Mozahler** [imoreapps/ffmpeg-avplayer-for-ios-tvos#33]
I used to get a thumbnail using this code:
      let mp: FFAVParser = FFAVParser()
     if mp.open(fileName) {
         thumbnail = mp.thumbnail(atTime: Double(fminf(20, Float(mp.duration)) / 2.0))
         mp = nil
      }

Now I tried this but openMedia comes back false, so thumbnail is nil (never assigned to)
        let mp: FFAVParser = FFAVParser()
        if (mp.openMedia(URL(string:fileName)!, withOptions: nil)) {
             thumbnail = mp.thumbnail(atTime: Double(fminf(20, Float(mp.duration)) / 2.0))
}

what am I doing wrong?

**Comment by imoreapps** [comment]
Just renew the demo license code, please re-try, thanks.
