### ISSUE TITLE
Mpeg2Ts support

### ISSUE THREAD

**Issue by a4tech** [imoreapps/ffmpeg-avplayer-for-ios-tvos#4]
I have compiled project and got issue on mpeg2ts stream files:

Could you help me to implement support for RAW TS stream ?

Here are 2 sample files:

http://sendfile.es/pokaz/560365---89rs.html
http://sendfile.es/pokaz/560366---d4yy.html

1) RAW format - which should be supported
2) Same file fixed by TS_Doctor

Both files should be able to play. Only Audio is working on it.

**Comment by imoreapps** [comment]
It seemed that i can not download these files, can you share them via Google Drive, Dropbox, Box, or OneDrive? Thanks.

**Comment by a4tech** [comment]
https://www.dropbox.com/s/g0b603knd8ro86b/tstTS3_fixed.ts?dl=0
https://www.dropbox.com/s/6x74wgpq2vsbnq4/tstTS3.ts?dl=0

This is TS from Sattelite which I save to file and try play by Your player.

It is mpeg2ts format.

Thanks !

**Comment by a4tech** [comment]
I did some changes and looks like files are playable.

Problem is that player does not play PipeFile. I mean:

I retrive data to a pipFile, ( test.ts ), I put NSURL to that file, but player can not make a playback for that.

"Failed to load video !"

I guess that it miss some function such as av_getcodecinfo() from the file and wait till stream appear in the file.

**Comment by imoreapps** [comment]
Please try to update the "avFormatName" property of FFAVPlayerController instance with "mjpeg" string value before you load it.

**Comment by a4tech** [comment]
It does not help. Faild to load video.

It is pipeFile. File URL to which i write constantly data with stream.

I did following change:

 // if (!self.mediaURL.isFileURL) {
    options[AVOptionNameAVProbeSize] = @(256*1024); // 256kb, default is 5Mb
    options[AVOptionNameAVAnalyzeduration] = @(5);  // default is 5 seconds
    options[AVOptionNameHttpUserAgent] = @"Mozilla/5.0";
 // }

 // if (self.avFormatName) {
    options[AVOptionNameAVFormatName] = @"mjpeg";
 // }

  [_avplayController openMedia:self.mediaURL withOptions:options];

**Comment by a4tech** [comment]
I have tried to play pipeFile by:

https://github.com/kolyvan/kxmovie

I noticed it has no problems. but It is quite old. I would cooperate to fix it in Your app.

**Comment by a4tech** [comment]
Do You think We can try to add support for loading movie from pipefile ?

**Comment by imoreapps** [comment]
We could not find any pipfile informations, can you provide more details about how to setup pipfile?

**Comment by imoreapps** [comment]
The latest version has already supported most of FFmpeg protocols, includes pipfile. Thanks.
