### ISSUE TITLE
Static linking is not allowed in LGPL

### ISSUE THREAD

**Issue by Naville** [imoreapps/ffmpeg-avplayer-for-ios-tvos#42]
![877a901c-e262-4fb1-a5be-4b3d2512c331](https://cloud.githubusercontent.com/assets/5205699/23139009/572fd62a-f7a2-11e6-899d-621dc539d291.png)
This means this "Paid Framework" and any code using it violates various licenses.
Use with caution, you have been warned

Close the issue as you like, but no company will buy this shit risking a lawsuit

![79a67174-e6af-491a-a3c9-440c2bd20355](https://cloud.githubusercontent.com/assets/5205699/23139283/87e72df8-f7a3-11e6-90c6-31854fb3bc65.png)
Also , I'm selling LLVM obfuscator : ) /s

Typical Chinese Developer

**Comment by Lessica** [comment]
這 iMoreApps 真的是魔幻現實主義欸，LGPL不允許 Static Linking 這人卻拿來賣錢，典型的大陸程序員
