### ISSUE TITLE
how to change video quality while video is playing?

### ISSUE THREAD

**Issue by kuldeep13990** [imoreapps/ffmpeg-avplayer-for-ios-tvos#45]
i want to change video quality like 360p, 480p, 720p while video is playing, is it possible to change?

if yes than can you suggest me how can i achieve that?

**Comment by imoreapps** [comment]
Yes, you can achieve this feature by following guide.

- for realtime video playback, you just need to create a new player instance then load new video   source.
- for non-realtime video playback, you need to create a new player instance and load new video source, then restore previous playback position when loading is done.

Good luck.
