### ISSUE TITLE
Link error for ARMv7 architectures

### ISSUE THREAD

**Issue by amedmund** [imoreapps/ffmpeg-avplayer-for-ios-tvos#46]
I build the app with tvOSAVPlayerTouch.framework on iPad mini and will get the error as below.

: "_AVOptionNameHttpHeader", referenced from:
: -[MediaViewController viewDidAppear:] in MediaViewController.o
: -[MediaViewController auth:finishedRefreshWithFetcher:error:] in MediaViewController.o
: "_OBJC_CLASS_$_NativeAVPlayerController", referenced from:
: Objc-class-ref in MediaViewController.o
: "_OBJC_CLASS_$_FFAVPlayerController", referenced from:
: Objc-class-ref in MediaViewController.o
: "_OBJC_CLASS_$_AVPLicense", referenced from:
: Objc-class-ref in AppDelegate.o
: Symbol(s) not found for architecture armv7
: Linker command failed with exit code 1 (use -v to see invocation)

**Comment by imoreapps** [comment]
Can you compile and run the demo project on your device?

**Comment by amedmund** [comment]
The demo project is failed too.
