### ISSUE TITLE
is there any interface get the video size?

### ISSUE THREAD

**Issue by phylony** [imoreapps/ffmpeg-avplayer-for-ios-tvos#49]
the api in the framework only supports set videoAspectRatio for the video;

but there are too many different size of videos, so can we obtain the video origin size by the frameworks.

**Comment by imoreapps** [comment]
Yes, you can query the "videoFrameSize" property of FFAVPlayerController class when you successfully opened video.

**Comment by phylony** [comment]
i tried the property,but the size is not the correct,and the video is streched。
http://139.196.154.105/Cordis/videoUpload/636334768773542727.mp4
this is the test url.you can see the video is 1080*1440,but it looks like 1440*1080 in video player

**Comment by phylony** [comment]
by the way,where can i buy the license?and do the project should be a long time support;

**Comment by imoreapps** [comment]
- It seemed that there is a rotation issue in framework.
- Please feel free to contact us via imoreapps@gmail.com for more details about license.
