### ISSUE TITLE
This videoplayer can't play rtsp well.

### ISSUE THREAD

**Issue by sljoai** [imoreapps/ffmpeg-avplayer-for-ios-tvos#7]
I used this videoplayer to play two rtsp streams, but one is "rtsp://218.204.223.237:554/live/1/66251FC11353191F/e7ooqwcfbqjoo80j.sdp", and it goes well; the other is "rtsp://m2.0427.com:554/pjxwzhtv", and it doesn't go well. When I run it, it shows me some information, following:
[rtsp @ 0x137867600] method SETUP failed: 454 Session Not Found
2015-11-19 10:33:03.650 AVPlayerDemo[367:86595] SETUP OPENGL SUCCESSFULLY!!!
[rtsp @ 0x137867600] method SETUP failed: 454 Session Not Found
[rtsp @ 0x137867600] method SETUP failed: 454 Session Not Found.
I don't know what's wrong with it. Can anybody help me?

**Comment by imoreapps** [comment]
The rtsp support of avplayer framework is based on the FFmpeg library, it's not very well for mobile platform, we will re-implement it based on the live555 library on next update. Thanks.

**Comment by fukemy** [comment]
hello. now it fully support rstp/rtmp?

**Comment by imoreapps** [comment]
Yes, it supports RSTP/RTMP protocols.

kemy do <notifications@github.com> 于2018年8月1日周三 下午6:05写道：
