### ISSUE TITLE
License question.

### ISSUE THREAD

**Issue by nrj** [imoreapps/ffmpeg-avplayer-for-ios-tvos#8]
Forgive me if this is mentioned elsewhere, but I did not see any mention of it in the README. In the AppDelegate I notice this line:

`[AVPLicense register:@"Phx7B6TjRVQHo7j8IiEWVHz7viL0t0WvVlZHv53Zw+lQlpM2czk2pHCUzXa0CnRlF80ozlggFNW/3Fh1JZR7h0b+g5MHn6jsx6t9dAbYlS8P4QRia7KpwGRddKTiFEx9abQakrk+8FXa4oRaoboG689pf288iWa6kBGsq/W72gIUXaHqkLAbZ4ljFaeGyWBhc9jV3l46D97vrqT6CG7Lxg=="];`

Can you elaborate on what this is? The library does not appear to function without it. I would like to use the `AVPlayerTouch.framework` and build a video player UI around it for tvOS. However if the licensing around this framework is subject to change or one day this key may just stop working, I probably won't bother.

**Comment by imoreapps** [comment]
This is a license of the framework, if you want to use the framework in your product, please purchase it,  
also license never expires. Thanks.

**Comment by fukemy** [comment]
where to purchase?

**Comment by imoreapps** [comment]
Thanks for your attention.


This is a charging framework ($399), one time payment, free update for
lifetime, it has very loose and flexible license, unlimited projects,
distributing binary products and commercial use etc. Our framework has
served more than 200 customers (companies and individual developers), such
as Lenovo, Simplo, iSmart Inc, INU CREATIVE & MEDIA, CANON HOUSE of USA,
Peep.im, Recordmob.com, Sphere Apps Inc., (Poland) Next! s.c. Sławomir Piela
, Bartłomiej Dryja, Camerail, China Railway Signal & Communication
Corporation Limited etc…


We accept PayPal payment, our PayPal account is imoreapps@hotmail.com


Our customer service will prepare pro license for you in 5 minutes when you
complete payment, then you just need to replace the demo license code with
your license code in the method "application:
didFinishLaunchingWithOptions:" of AppDelegate class. That's it!


- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    // Override point for customization after application launch.

    *[**AVPLicense register:@"Put your License Code Here"**];*

    return YES;

}


If you have any question, please feel free to contact us.  Have a nice day.

kemy do <notifications@github.com> 于2018年8月1日周三 下午6:22写道：

**Comment by IntZer0** [comment]
Thanks for your project but i have never pay for free things :))
{"cn":"IMOREAPPS TEAM (DEMO LICENSE)","dv":true,"dd":true,"hwd":true,"bd":1577864744.8907809,"protocol":"all","ed":1893483944.8907809,"pid":"P100"}

btw, work on your license system

**Comment by PlasmaSoftUK** [comment]
> Thanks for your project but i have never pay for free things :))
> {"cn":"IMOREAPPS TEAM (DEMO LICENSE)","dv":true,"dd":true,"hwd":true,"bd":1577864744.8907809,"protocol":"all","ed":1893483944.8907809,"pid":"P100"}
> 
> btw, work on your license system

Looks like the developer has abandoned this project, I'd be interested to know how you got to that string! :) 

Plasma

**Comment by fukemy** [comment]
if your choice is using ffmgep, just search for ijkplayer, it's best and free for android/ios. dont use this bad project
