### ISSUE TITLE
DEMO VERSION? License needed?

### ISSUE THREAD

**Issue by tne7laa** [imoreapps/ffmpeg-avplayer-for-ios-tvos#9]
Can someone tell me how to get the text "DEMO VERSION" gone from the video?
In other issue someone talks about AVPLicense register but can't find anything where i can purchase.
Thanks.

**Comment by xiaoyongaz** [comment]
same question, it would be nice to show more detail about the avplayer

**Comment by alijnclarke** [comment]
+1

**Comment by alijnclarke** [comment]
Don't really want to start work on a project using this if i can't get rid of the 'demo version' text.. would be nice if we could understand a little more about the license @iMoreApps

**Comment by fpzeng** [comment]
I failed to find libs.gz sources. Anybody can tell me where to get it?

**Comment by imoreapps** [comment]
This is a pay framework, also has very loose and flexible license. if you need more details about its license, please contact us via imoreapps@gmail.com
